# Site settings
title: Visit Britain
client:
  name: Visit Britain
  link: https://www.visitbritain.com/gb/en/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Take a look at our handpicked selection of unmissable microgap experiences from coast, to country, to city. Pick your perfect hotel offer from across the UK and begin your very own microgap adventure today.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/visit-britain" # the subpath of your site, e.g. /blog/
img:     "/visit-britain/_assets/img"
css:     "/visit-britain/_assets/css"
js:      "/visit-britain/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed